---
title: "Call Loads by Time of Day"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(lubridate)
library(ggplot2)

source(here::here("src", "Profiling", "joining_albemarle_charlottesville.R"))
```

```{r include = FALSE}
new_ems_data <- new_ems_data %>%
  ## Breaking down time of day info
  mutate(psap_time_of_day = ymd_hms(paste("2020-01-01", strftime(incident_psap_call_date_time, format="%H:%M:%S"), sep = " ")),
         psap_hour = hour(psap_time_of_day),
         psap_minute = minute(psap_time_of_day)) %>%
  ## Categorizing primary impressions manually:
  mutate(primary_impression_category = case_when(str_detect(situation_provider_primary_impression_code_and_description, "lcohol") ~ "Abuse of Alcohol",
                                                 str_detect(situation_provider_primary_impression_code_and_description, "Abuse") ~ "Abuse of Substance",
                                                 str_detect(situation_provider_primary_impression_code_and_description, "Allergic") ~ "Allergic Reaction",
                                                 str_detect(situation_provider_primary_impression_code_and_description, "OB") ~ "OB",
                                                 str_detect(situation_provider_primary_impression_code_and_description, "Endocrine") ~ "Endocrine",
                                                 str_detect(situation_provider_primary_impression_code_and_description, "GI") ~ "GI/GU",
                                                 str_detect(situation_provider_primary_impression_code_and_description, " - ") ~ str_extract(situation_provider_primary_impression_code_and_description, "[^-]+"), 
                                                 !str_detect(situation_provider_primary_impression_code_and_description, " - ") ~ str_extract(situation_provider_primary_impression_code_and_description, "[^\\(]+")),
         primary_impression_category = trimws(primary_impression_category))
```

```{r include = FALSE}
top_impressions <- new_ems_data %>% 
  filter(!is.na(situation_provider_primary_impression_code_and_description)) %>%
  group_by(situation_provider_primary_impression_code_and_description) %>% 
  count() %>% 
  ungroup() %>%
  top_n(5) %>%
  arrange(desc(n))

top_impressions <- top_impressions$situation_provider_primary_impression_code_and_description

top_impression_categories <- new_ems_data %>% 
  filter(!is.na(primary_impression_category)) %>%
  group_by(primary_impression_category) %>% 
  count() %>% 
  ungroup() %>%
  top_n(10) %>%
  arrange(desc(n))

top_impression_categories <- top_impression_categories$primary_impression_category
```

Start with a baseline call load density for various impression categories:

``` {r}
new_ems_data %>%
  filter(!is.na(situation_provider_primary_impression_code_and_description), 
         !is.na(psap_time_of_day), 
         primary_impression_category %in% top_impression_categories) %>%
  ggplot() +
  geom_density(aes(x = psap_time_of_day, color = primary_impression_category), alpha = 0.3) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45))
```

Some evidence of changes in call load pre/post COVID. But it seems to be more driven by alcohol related incidents rather than overall changes:

```{r}
new_ems_data %>% 
  mutate(is_recent = ifelse(incident_date > "2020-03-01", "Post 03/01/2020", "Pre 03/01/2020")) %>%
  filter(!is.na(situation_provider_primary_impression_code_and_description), 
         !is.na(psap_time_of_day), 
         primary_impression_category %in% top_impression_categories) %>%
  group_by(is_recent) %>%
  ggplot() +
  geom_density(aes(x = psap_time_of_day, color = primary_impression_category), alpha = 0.3) +
  theme_minimal() +
  facet_grid(is_recent ~ .) +
  theme(axis.text.x = element_text(angle = 45),
        legend.position = "none")
```

```{r}

new_ems_data %>%
  filter(!is.na(situation_provider_primary_impression_code_and_description), 
         !is.na(psap_time_of_day), 
         primary_impression_category %in% top_impression_categories) %>%
  ## Can include this stuff if you want to facet by agency
  # group_by(agency_name) %>%
  # mutate(n = n()) %>%
  # filter(n > 1000) %>%
  ggplot() +
  geom_density(aes(x = psap_time_of_day, color = primary_impression_category), alpha = 0.3) +
  theme_minimal() +
  # facet_grid(~agency_name) +
  theme(axis.text.x = element_text(angle = 45))

```


