---
title: "complaint_EDA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r prep}
library(stringr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(lubridate)
library(plotly)

## Read in data
source(here::here("src", "Profiling", "joining_albemarle_charlottesville.R"))

ems_full <- ems_full %>% 
  mutate(incident_date = ymd(incident_date), 
         yr = as.factor(year(incident_date)), 
         mo = as.factor(month(incident_date)), 
         dy = as.character(day(incident_date)))
```

```{r}
plot_data <- ems_full %>% filter(incident_complaint_reported_by_dispatch %in% c("Breathing Problem")) %>%
  group_by(yr, mo, source) %>%
  count() %>%
  filter(yr != 2016)

cbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#CC79A7", "#F0E442", "#0072B2", "#D55E00")

ggplot(plot_data) +
  geom_point(aes(x = as.numeric(mo), y = n, color = yr), alpha = 0.7, shape = 1) +
  geom_line(aes(x = as.numeric(mo), y = n, color = yr)) +
  scale_colour_manual(values=cbPalette) +
  facet_grid(~source)
```

```{r}
plot_complaint_volume <- function(data, vars) {
  
  plot_data <- data %>% filter(incident_complaint_reported_by_dispatch %in% vars) %>%
    mutate(mo_yr = dmy(paste0("01-", mo, "-", yr))) %>%
    group_by(mo_yr, incident_complaint_reported_by_dispatch) %>%
    count()
  
  cbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#CC79A7", "#F0E442", "#0072B2", "#D55E00")
  
  ggplot(plot_data) + 
    geom_line(aes(x = mo_yr, y = n, color = incident_complaint_reported_by_dispatch), alpha = 1) + 
    geom_point(aes(x = mo_yr, y = n, color = incident_complaint_reported_by_dispatch), alpha = 0.7) +
    geom_vline(xintercept = dmy("02-01-2020"), linetype = "dashed", alpha = 0.8) +
    scale_color_manual(values = cbPalette) +
    facet_wrap(~incident_complaint_reported_by_dispatch, ncol = 1)
}
```


```{r}
## Complaints to view
# unique(ems_full$incident_complaint_reported_by_dispatch)
top_complaints <- ems_full %>% 
  group_by(incident_complaint_reported_by_dispatch) %>% 
  summarize(n = n()) %>% 
  top_n(3, n)

complaints <- top_complaints$incident_complaint_reported_by_dispatch

## Plot
plot_complaint_volume(ems_full, vars = complaints)
```

```{r}
#vars <- complaints
top_complaints <- ems_full %>% 
  group_by(incident_complaint_reported_by_dispatch) %>% 
  summarize(n = n()) %>% 
  top_n(8, n)

vars <- top_complaints$incident_complaint_reported_by_dispatch

plot_data <- ems_full %>% filter(incident_complaint_reported_by_dispatch %in% vars) %>%
  mutate(mo_yr = dmy(paste0("01-", mo, "-", yr))) %>%
  group_by(mo_yr, incident_complaint_reported_by_dispatch) %>%
  count()

cbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#CC79A7", "#F0E442", "#0072B2", "#D55E00")

key <- highlight_key(plot_data, ~incident_complaint_reported_by_dispatch)

plt <- ggplot(key) + 
  geom_line(aes(x = mo_yr, y = n, color = incident_complaint_reported_by_dispatch), alpha = 1) + 
  #geom_point(aes(x = mo_yr, y = n), alpha = 0.7) +
  geom_vline(xintercept = dmy("02-01-2020"), linetype = "dashed", alpha = 0.8) +
  scale_color_brewer(palette = "Set2") +
  labs(title = "Call Volume by Reported Complaint", x = "Date", y = "Incidents per month") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))

plt_highlight <- ggplotly(plt, tooltip = ".crossTalkKey") %>% 
  highlight(on = "plotly_hover", off = "plotly_doubleclick") %>%
  layout(showlegend = FALSE)

plt_highlight

```

```{r }


```
